downloader/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'downloader'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^download/$', views.download, name='download')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

igdown/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('downloader.urls'))
]

downloader/views.py
from wsgiref.util import FileWrapper

from django.shortcuts import render
from django.http.response import HttpResponse

from .ig_downloader import InstagramDownloader


def home(request):
    return render(request, 'downloader/index.html')

def download(request):
    download_url = request.POST['download_url']
    downloader = InstagramDownloader(download_url)
    downloader.download()

    filename = downloader.get_output_filename()
    wrapper = FileWrapper(open(filename, mode='rb'))
    response = HttpResponse(wrapper)
    response['Content-Disposition'] = "attachment; filename={}".format(filename)

    return response

downloader/templates/downloader/index.html
<html lang="en">
    {% load staticfiles %}
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
        <title>IGDown - Instagram downloader</title>

        <link rel="icon" href="{% static 'downloader/images/favicon.png' %}">
        
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        
        <link rel="stylesheet" href="{% static 'downloader/styles/style.css' %}">
    </head>
    <body>
        <main>
            <div class="row white-text">
                <div class="col s12 center">
                    <h1>IGDown</h1>
                    <h6 id="subheader" class="grey-text text-lighten-1">Download Instagram photos and videos with one click</h6>

                    <div class="row">
                        <form action="{% url 'downloader:download' %}" method="POST" class="col s12 m8 l6 offset-m2 offset-l3" id="download_form">
                            {% csrf_token %}

                            <div class="input-field col s12">
                                <i class="material-icons prefix">insert_link</i>
                                <input type="url" name="download_url" id="download_url" required="required" />
                                <label for="download_url">Enter Instagram media URL</label>
                            </div>
                            
                            <button type="submit" class="waves-effect waves-light btn-large z-depth-3">
                                Download
                                <i class="material-icons right">file_download</i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </main>

        <footer class="page-footer teal">
            <div class="footer-copyright">
                <div class="container">
                © 2017 wencakisa
                <a class="grey-text text-lighten-4 right" href="https://github.com/wencakisa/igdown/" target="_blank">
                    <strong>Project is open-sourced <i class="material-icons" id="code_icon">code</i></strong>
                </a>
                </div>
            </div>
        </footer>

        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        <script type="text/javascript" src="{% static 'downloader/scripts/script.js' %}"></script>
    </body>
</html>